server:
  port: 8000

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: patient-data-collector
          uri: lb://SERVICIO-PATIENT-DATA
          predicates:
            - Path=/conjunta/2p/vital-signs/**

        - id: health-analyzer
          uri: lb://SERVICIO-HEALTH-ANALYZER
          predicates:
            - Path=/conjunta/2p/health/**

        - id: care-notifier
          uri: lb://SERVICIO-CARE-NOTIFIER
          predicates:
            - Path=/conjunta/2p/notifier/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
